version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1270
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"  # Внешний порт 5435, внутренний 5432

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1270
    ports:
      - "8081:8080"  # Внешний порт 8080, внутренний 8080

  frontend:
    build:
      context: ./ # Путь к директории с Dockerfile для фронтенда
      dockerfile: frontend/Dockerfile # Убедитесь, что у вас есть Dockerfile в этой директории
    container_name: frontend
    ports:
      - "3000:3000"  # Внешний порт 3000, внутренний 3000 (или другой порт, который использует ваше приложение)

volumes:
  frontend-build:
  db_data:
